version: R2.{build}
os: Visual Studio 2015
environment:
  DNX_FEED: https://www.nuget.org/api/v2
install:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
before_build:
- ps: "\"&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}\" "
- dnvm install 1.0.0-beta7
- dnvm list
- dnvm use 1.0.0-beta7
- npm cache clean
- npm install -g gulp bower
- dnu restore
build:
  publish_wap: true
  verbosity: minimal
after_build:
- cmd: dir C:\projects\344-web-engineering\
test_script:
- cmd: dnu restore
- cmd: dnx -p C:\projects\344-web-engineering\src\SE344Test\project.json test
artifacts:
- path: '\artifacts\bin\SE344\'
  name: Primary Project Results
deploy: off
