USE [master]
GO

/****** Object:  Database [hodge_podge]    Script Date: 12/2/2015 6:39:54 PM ******/
DROP DATABASE [hodge_podge]
GO

/****** Object:  Database [hodge_podge]    Script Date: 12/2/2015 6:39:54 PM ******/
CREATE DATABASE [hodge_podge]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'hodge_podge', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\hodge_podge.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'hodge_podge_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\hodge_podge_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [hodge_podge] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [hodge_podge].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [hodge_podge] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [hodge_podge] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [hodge_podge] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [hodge_podge] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [hodge_podge] SET ARITHABORT OFF 
GO

ALTER DATABASE [hodge_podge] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [hodge_podge] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [hodge_podge] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [hodge_podge] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [hodge_podge] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [hodge_podge] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [hodge_podge] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [hodge_podge] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [hodge_podge] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [hodge_podge] SET  DISABLE_BROKER 
GO

ALTER DATABASE [hodge_podge] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [hodge_podge] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [hodge_podge] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [hodge_podge] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [hodge_podge] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [hodge_podge] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [hodge_podge] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [hodge_podge] SET RECOVERY FULL 
GO

ALTER DATABASE [hodge_podge] SET  MULTI_USER 
GO

ALTER DATABASE [hodge_podge] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [hodge_podge] SET DB_CHAINING OFF 
GO

ALTER DATABASE [hodge_podge] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [hodge_podge] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [hodge_podge] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [hodge_podge] SET  READ_WRITE 
GO


